/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Entry = IDL.Record({
  'bSection' : IDL.Vec(IDL.Nat),
  'date' : Time,
  'game' : IDL.Text,
  'cuttingAmount' : IDL.Nat,
  'multiplyValue' : IDL.Nat,
  'numbers' : IDL.Vec(IDL.Nat),
  'party' : IDL.Text,
  'cuttingType' : IDL.Int,
  'aSection' : IDL.Vec(IDL.Nat),
  'cuttingPercentage' : IDL.Nat,
});

export const idlService = IDL.Service({
  'deleteData' : IDL.Func([Time, IDL.Text, IDL.Text], [], []),
  'getAllData' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getDataByDate' : IDL.Func([Time], [IDL.Vec(Entry)], ['query']),
  'getDataByParty' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
  'saveData' : IDL.Func(
      [
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Vec(IDL.Nat),
        IDL.Vec(IDL.Nat),
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Entry = IDL.Record({
    'bSection' : IDL.Vec(IDL.Nat),
    'date' : Time,
    'game' : IDL.Text,
    'cuttingAmount' : IDL.Nat,
    'multiplyValue' : IDL.Nat,
    'numbers' : IDL.Vec(IDL.Nat),
    'party' : IDL.Text,
    'cuttingType' : IDL.Int,
    'aSection' : IDL.Vec(IDL.Nat),
    'cuttingPercentage' : IDL.Nat,
  });
  
  return IDL.Service({
    'deleteData' : IDL.Func([Time, IDL.Text, IDL.Text], [], []),
    'getAllData' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getDataByDate' : IDL.Func([Time], [IDL.Vec(Entry)], ['query']),
    'getDataByParty' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
    'saveData' : IDL.Func(
        [
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Vec(IDL.Nat),
          IDL.Vec(IDL.Nat),
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };